### ISSUE TITLE
How to get checkbox checked status not value?

### ISSUE THREAD

**Issue by KevinKelbie** [bluebill1049/react-hook-form#189] opened 2019-08-06 11:50 UTC
It seems like when using checkboxes it defaults to giving you the `e.target.value` rather than `e.target.checked`. How can I get the checked status rather than the value?

Thanks in advance.

**Comment by bluebill1049** [comment] 2019-08-06 11:58
Hmmm, I have encountered this issue three times now. 

The difficulty that I am having right now is if you defined a value for checkbox, should you get its `value` or `checked`? if you want only `checked` then what about the user who wants the `value`?

hence I decide to have the following code (in the lib):

`if (isCheckBox(type)) return checked ? value || checked : false;`

if checked you will always get the `value`. for unchecked return `false`. if you only want to know checked or not, you can convert the `value` to boolean.

hope this makes sense, and happy for the good alternative suggestion.

**Comment by KevinKelbie** [comment] 2019-08-06 12:12
I noticed I was getting either `on` or `false` which I thought was an issue on my end but it sounds like its excepted behavior based on what you said. I want it to return `true` and `false` but the problem is that if you define the value to be true in the html its a string not a boolean which is mildly inconvenient.

Is there a way to specify in the `register` something like:

    register({checkbox: "checked"}) // or 
    register({checkbox: "value"}) 

Then in `react-hook-form` do:

    if (isCheckBox(type)) return e.target[checkbox]

**Comment by bluebill1049** [comment] 2019-08-06 12:19
what about do this `!!value` if all you want is true or false

**Comment by KevinKelbie** [comment] 2019-08-06 12:27
I could but that would require doing that for all my checkboxes in the `onSubmit` callback which doesn't seem like the right place to do it. In the meantime I'll do that but I suggest coming up with some way to specify what you want in the `register`.

**Comment by bluebill1049** [comment] 2019-08-06 21:37
i think i have found the solution:

3.21.8-beta.1

please help test above beta version

**Comment by KevinKelbie** [comment] 2019-08-07 08:46
Just installed it. Seems to be working for me.

I also noticed another potential bug but I'm not sure. Is it expected behavior for nothing to be returned in the `handleSubmit` when using an checkbox input and `ref={register()}`? It only returns the result if you use `register` or `register({})` (with the object)

**Comment by bluebill1049** [comment] 2019-08-07 09:32
that's not a bug `ref` takes a callback, going to publish the version and close this issue.

**Closed by bluebill1049** 2019-08-07 09:32 UTC
Labels: question

**Comment by Zik42** [comment] 2019-12-22 17:09
@bluebill1049  onSubmit returns value instead of checked anyway.

**Comment by bluebill1049** [comment] 2019-12-22 21:12
@Zik42 it depends if you have a value attribute in the checkbox.
