### ISSUE TITLE
getValues() and watch() don't work correctly with array fields

### ISSUE THREAD

**Issue by zernie** [bluebill1049/react-hook-form#134] opened 2019-07-18 13:39 UTC
**Describe the bug**
`getValues()` and `watch()`  return incorrect values when working with array fields.

**To Reproduce**
```
import React from "react";
import ReactDOM from "react-dom";
import useForm from "react-hook-form";

function App() {
  const { register, getValues, watch } = useForm({
    defaultValues: { test: [0, 1] }
  });
  const test = watch("test");

  return (
    <form>
      <h3>getValues: {JSON.stringify(getValues())}</h3>
      <h3>watch: {test}</h3>
      {/* <h3>watch(): {JSON.stringify(watch())}</h3> */}

      <input name="test[0]" ref={register} type="checkbox" />
      <input name="test[1]" ref={register} type="checkbox" />
    </form>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

https://codesandbox.io/embed/react-hook-form-basic-qgkkp
**Expected behavior**
* `getValues()` should have returned `{test: [0,1]}` (instead got `{}` on first render and `{"test[0]":"on","test[1]":false}` after clicking on the first checkbox)
* `watch('test')` should have returned `[0,1]`, instead got: `undefined`.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 75

**Comment by zernie** [comment] 2019-07-18 13:45
Also: component doesn't rerender on checkbox uncheck. Calling `watch()` fixes that somehow

**Comment by zernie** [comment] 2019-07-18 13:54
@bluebill1049 I'm not sure if that's a bug, but `watch(anyfield)` returns undefined on first render. I've updat the example.

**Comment by bluebill1049** [comment] 2019-07-19 01:35
@zernie thanks for the issue report. I will look into `getValues()` and `watch()` issue over the weekend.

> I'm not sure if that's a bug, but watch(foo) returns undefined on the first render even though foo is set in default values. I've updated the example.

This is expected: `watch` have the second argument for a default value, because first render, all the inputs would not have been `register` just yet.

**Comment by bluebill1049** [comment] 2019-07-19 04:45
> watch('test') should have returned [0,1], instead got: undefined.

I think this is not an issue when you want to watch fields,  you probably should do the following:

`watch(['test[0]', 'test[1]']`

**Comment by bluebill1049** [comment] 2019-07-19 04:56
> Also: component doesn't rerender on checkbox uncheck. Calling watch() fixes that somehow

because `watch('test')` is not wathcing anything, it worked the first time, because it was updating the `formState` with `touched` 

https://codesandbox.io/s/react-hook-form-basic-n53gm

**Comment by bluebill1049** [comment] 2019-07-19 05:03
fixed `getValues()`

https://codesandbox.io/s/react-hook-form-basic-n53gm

**Comment by bluebill1049** [comment] 2019-07-19 05:41
`getValues()` fix have been published

https://github.com/bluebill1049/react-hook-form/releases/tag/v3.18.7

**Comment by bluebill1049** [comment] 2019-07-19 06:27
for `getValues()`

return 
Option1: `{"test[0]":"on","test[1]":false}`
vs
Option2: `{test: [0,1]}`

I was thinking some sort of argument, which lead to `option2` and leave default option1 unchanged.

`getValues({ combine: true })` to return option 2
`getValues()` to return option 1

**Comment by zernie** [comment] 2019-07-19 07:52
> This is expected for watch and getValues: because first render, all the inputs would not have been register just yet.
> watch have the second argument for a default value.

ok, but I think this should be outlined in the docs

> I think this is not an issue when you want to watch fields, you probably should do the following:
>watch(['test[0]', 'test[1]']

I have to disagree, this is really clumsy, especially when you have a dynamic sized array

> because watch('test') is not wathcing anything, it worked the first time, because it was updating the formState with touched

Which means that fixing `watch` behaviour for array fields would also fix this as well, correct?


> For getValues() issue
> Return value:
> 
> Option1: {"test[0]":"on","test[1]":false}
> vs
> Option2: {test: [0,1]}
> 
> I like option1 because it's flat and you don't have to dive deep into the object
> eg: data[3].test this is going to create a problem.
> 
> with option1 you can access data with confident: data['test[0]']
> 
> but I would like to hear your or anyone concern over this.

Option 2 provides a much better DX (who wants to manually build a string to access a field?) and follows the principle of least astonishment.

Thanks!

**Comment by zernie** [comment] 2019-07-19 12:06
> Agree, It makes sense for defaultValues to be able to get value in watch() first render, but when I am having the following
> 
> <input type="test" defaultValue="" />
> 
> then it's not going to work as expected, because it's not rendered just yet, so I was trying to be consistent there.

I think `defaultValue` should just override `defaultValues`. But maybe library should output a warning in this case?

> what about some type of argument to shape the result from getValues({ flatten: false }), any good suggestion?
Love it! This way we could get the benefits of both approaches. Just gonna need the same argument for `watch`.

**Comment by bluebill1049** [comment] 2019-07-19 12:08
> I think defaultValue should just override defaultValues. But maybe library should output a warning in this case?

I think have `defaultValues` inject in to `watch()` as default makes sense, I will document that in the website to reduce the confusion.

**Comment by bluebill1049** [comment] 2019-07-19 12:09
- [ ] defaultValues inject default value into watch

**Comment by zernie** [comment] 2019-07-19 12:09
@bluebill1049 I think the second argument should be deprecated then (so there is a single source of truth)

**Comment by bluebill1049** [comment] 2019-07-19 12:14
@zernie have a look my todo list, see if you happy with it.

**Comment by zernie** [comment] 2019-07-19 12:15
@bluebill1049 what do you think about a warning when overriding `defaultValues` with `defaultValue` and deprecating second argument for `watch`?

**Comment by bluebill1049** [comment] 2019-07-19 12:17
@zernie I think I will leave the second argument, cause we use that at work already. I think `watch` API can stay as it is, just needs to support `watch('test')` to get the entire array or object

**Comment by bluebill1049** [comment] 2019-07-19 12:20
@zernie I may break these into separate releases, going to take me sometimes 🙏 but keep you posted here.

**Comment by bluebill1049** [comment] 2019-07-22 12:33
@zernie beta version: react-hook-form@3.19.0-beta.1

**Comment by bluebill1049** [comment] 2019-07-22 12:41
**`watch` API update:**

1. `watch` return default value change:
`watch(['test', 'test1']) // deafult value return [undefined, undefined] instead of undefined`
`watch() // default value return {} instead of undefined`

2. `watch` integrate with `defaultValues`
`watch` will inherit from data in `defaultValues`, but watch function arguments remain unchanged. second argument `defaultValue` will overwrite data in `defaultValues` which set up in `useForm()`

3. `watch` now support nested object look up
eg
```
  const data = watch('test');
  console.log(data);

    <form>
      <input name="test[0]" ref={register} />
      <input name="test[1]" ref={register} />
    </form>
```
this above example will watch both `test[0]` and `test[1]`

**`defaultValues` update:**

`defaultValues` now support nested object, eg:
```
const { register } = useForm({
  defaultValues: { test: {data: [1, 2]}},
})
```

**`getValues` update:**

`getValues` now support `nest` argument to return data in a nested format, eg:

```
getValues(); // {'test[0]': 1, 'test[1]': 2}
getValues({ nest: true }); // {test: [1,2]}
```

**Comment by zernie** [comment] 2019-07-25 07:59
@bluebill1049 that's great, thanks! This issue can be closed, methinks

**Comment by bluebill1049** [comment] 2019-07-25 08:14
Thanks @zernie I will close this once it’s published.

**Comment by bluebill1049** [comment] 2019-07-26 08:12
This feature have been released: https://github.com/bluebill1049/react-hook-form/releases/tag/v3.19.0

**Closed by bluebill1049** 2019-07-26 08:12 UTC
Labels: enhancement, feature

**Comment by douglasncon** [comment] 2020-08-18 17:50
Hi you guys! Nice thread and thanks for the solution! I ran into the same scenario as @zernie and have nested getValues() worked like a charm. 
Can you just please add that to the documentation? 
![image](https://user-images.githubusercontent.com/20860629/90547538-0e3aca80-e162-11ea-912f-9eccf58464f4.png)

**Comment by bluebill1049** [comment] 2020-08-18 22:41
> Hi you guys! Nice thread and thanks for the solution! I ran into the same scenario as @zernie and have nested getValues() worked like a charm.
> Can you just please add that to the documentation?
> ![image](https://user-images.githubusercontent.com/20860629/90547538-0e3aca80-e162-11ea-912f-9eccf58464f4.png)

would you like to send us PR?

**Comment by fddias87** [comment] 2022-04-26 13:57
Hi,

This seems to stop working since version ```7.20.0```.

> **`watch` API update:**
> 
> 3. `watch` now support nested object look up
>    eg
> 
> ```
>   const data = watch('test');
>   console.log(data);
> 
>     <form>
>       <input name="test[0]" ref={register} />
>       <input name="test[1]" ref={register} />
>     </form>
> ```
> 
> this above example will watch both `test[0]` and `test[1]`

It was on purpose?

Thanks,
Fabio Dias.

**Comment by Moshyfawn** [comment] 2022-04-26 19:37
> @fddias87: This seems to stop working since version 7.20.0.

Works as intended: see [this example](https://codesandbox.io/s/great-perlman-4ky59k?file=%2Fsrc%2FApp.tsx)
